name: 'Generate Acknowledgements from used Swift Packages'
description: 'Collate all LICENSE files from used Swift Packages and write a Acknowledgement.plist'
inputs:
  SPM_CHECKOUT_DIR:
    description: 'Location of the SPM Checkout directory'
    required: true
  FILE_NAME:
    description: 'The filename/path where we write the Acknowledgement.plist'
    required: true
outputs:
  PLAIN_TEXT:
    description: 'We provide PLAIN_TEXT version of the results'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'mic'
  color: 'blue'
